name: Deploy ginkss-dot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Code.
        uses: actions/checkout@v3

      # Node 버전 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 모듈 설치
      - name: Install Dependencies
        run: npm install

      # .env 키 세팅
      - name: Setting .env
        run: |
          echo "REACT_APP_SERVICE_ID = ${{ secrets.REACT_APP_SERVICE_ID }}" >> .env
          echo "REACT_APP_TEMPLATE_ID = ${{ secrets.REACT_APP_TEMPLATE_ID }}" >> .env
          echo "REACT_APP_PUBLIC_KEY = ${{ secrets.REACT_APP_PUBLIC_KEY }}" >> .env

      # 빌드
      - name: Build Project
        run: npm run build --if-present
        env:
          CI: false

      # AWS 계정 정보
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # AWS S3 배포
      - name: Deploy to S3
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region ap-northeast-2 build s3://ginkss --delete

      # CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
